# This is a template parameter used by guic (guidon cli).
[variables]
project_name = "test-inputfile"
app_name = "TestInputfileWva"
package_id = "org.omusubi.aki.wva.test_inputfile"
version_code = "1"
version_name = "0.1"
#load_url = "https://appassets.androidplatform.net/assets/pre.html"
load_url = "https://aki.omusubi.org/test-inputfile/"
#
compile_sdk_version = "36"
target_sdk_version = "36"
min_sdk_version = "28"
